### ISSUE TITLE
Installable through pip?

### ISSUE THREAD

**Issue by arve0** [anthonymayer/scaffold-py#6]
First off, nice work. :+1: I like the simplicity compared to [pyscaffold](https://github.com/blue-yonder/pyscaffold).

Is the package published to pypi? Can't seem to find it.

Also, @Aaronontheweb might be interested to depreciating his package?

**Comment by Aaronontheweb** [comment]
Cool, I had no idea this existed! I'm not super active in Python anymore (never really was, `pyscaffold` was a fun way for me to learn it though,) so I'd be happy to deprecate the pip package and swap it out with this one if @anthonymayer it up for it.

**Comment by Aaronontheweb** [comment]
Err, I mean scaffold-py :p

**Comment by anthonymayer** [comment]
Hey @arve0, thanks a lot. I'd be alright with putting this under pip, and I'd thought about it, but it didn't quite seem worth it, because I found https://github.com/audreyr/cookiecutter. If you think it is, I'm happy to do it though.

**Comment by arve0** [comment]
@anthonymayer Thanks for the pointer, I'll look into it. I guess it's not working right now, according to #7? If you ever find the time, a `./setup sdist upload` would be nice.
